CREATE TABLE CLIENT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11)
);

CREATE TABLE PRODUCT (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DESC VARCHAR(100),
    UNITY_PRICE NUMERIC(20,2)
);

CREATE TABLE ORDERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENT_ID INTEGER REFERENCES CLIENT (ID),
    ORDER_DATE TIMESTAMP,
    STATUS VARCHAR(20),
    TOTAL NUMERIC(20,2)
);

CREATE TABLE ORDER_ITEM (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INTEGER REFERENCES ORDERS (ID),
    PRODUCT_ID INTEGER REFERENCES PRODUCT (ID),
    QTD INTEGER
);

CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);